import type { AppSettings } from './types'

export const DEFAULT_SETTINGS: AppSettings = {
  destinationMode: 'drive',
  driveId: null,
  folder: null,
  volumeLabel: 'SUMMERCART',
  language: 'en',
  theme: 'gallery',
  downloadMenu: true,
  downloadMetadata: true,
  createFolders: true,
  downloadEmulators: true,
  emulators: { nes: true, snes: true, gb: true, sms: true, chf: true },
  installDDIPL: false,
  ddiplSource: null,
  copyRoms: true,
  romSources: [],
  archiveSources: [],
  copyAllTypes: true,
  romTypes: { n64: true, nes: true, snes: true, gb: true, sms: true, chf: true, ndd: true },
  createSaves: true,
  includeSubdirs: true,
  overwrite: false,
  organizeRoms: false,
  copyCheats: false,
  stage: false,
  verify: true,
  preparedSource: null,
  formatOptions: { fullFormat: false, filesystem: 'fat32' }
}
